import { useEffect, useState } from "react";
import { Activity, Bell, CalendarDays, Clock3, FileText, HeartPulse, LogOut, RefreshCw, Settings, UserRound, Users, X } from "lucide-react";
import { getProfessionalAppointments, getProfessionalAvailability, getProfessionalOverview, getProfessionalPatients, getUserProfile, updateProfessionalAppointment } from "./services/api";
import "./professional.css";

const formatDate = (value) => new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" });
const navItems = [["overview", Activity, "Overview"], ["appointments", CalendarDays, "Appointments"], ["patients", Users, "Patients"], ["consultations", FileText, "Consultations"], ["availability", Clock3, "Availability"], ["notifications", Bell, "Notifications"], ["resources", HeartPulse, "Resources"], ["profile", UserRound, "Profile"], ["settings", Settings, "Settings"]];

export default function ProfessionalApp({ user, onLogout }) {
  const [page, setPage] = useState("overview"); const [error, setError] = useState(""); const [authChecked, setAuthChecked] = useState(false);
  useEffect(() => { let cancelled = false; const verify = async () => { try { const result = await getUserProfile(); if (result.user.role !== "PROFESSIONAL") throw new Error("Professional access required."); if (!cancelled) { localStorage.setItem("mental_health_user", JSON.stringify(result.user)); setAuthChecked(true); } } catch (e) { if (!cancelled) { setError(e.message); onLogout(); } } }; verify(); return () => { cancelled = true; }; }, [onLogout]);
  if (!authChecked) return <div className="professional-state"><RefreshCw className="professional-spin" /> Verifying secure session…</div>;
  return <div className="professional-shell"><aside className="professional-sidebar"><div className="professional-brand"><HeartPulse size={22} /><span>MindCare<br /><small>Professional Dashboard</small></span></div><nav>{navItems.map(([id, Icon, label]) => <button className={page === id ? "active" : ""} key={id} onClick={() => { setPage(id); setError(""); }}><Icon size={17} /> {label}</button>)}</nav><button className="professional-logout" onClick={onLogout}><LogOut size={16} /> Log out</button></aside><main className="professional-main"><header className="professional-topbar"><div><span className="professional-kicker">Professional</span><h1>{page[0].toUpperCase() + page.slice(1)}</h1></div><span>{user?.name}</span></header>{error && <div className="professional-error"><X size={15} />{error}</div>}<ProfessionalContent page={page} onError={setError} /></main></div>;
}

function State({ loading, error }) { if (loading) return <div className="professional-state"><RefreshCw className="professional-spin" /> Loading…</div>; if (error) return <div className="professional-state"><p>{error}</p></div>; return null; }
function ProfessionalContent({ page, onError }) { if (page === "overview") return <Overview onError={onError} />; if (page === "appointments") return <Appointments onError={onError} />; if (page === "patients") return <Patients onError={onError} />; if (page === "consultations") return <Unavailable title="Consultations" message="Consultation records are not available in the current database schema." />; if (page === "availability") return <Availability onError={onError} />; if (page === "notifications") return <Unavailable title="Notifications" message="No professional-specific notifications are available." />; if (page === "resources") return <Unavailable title="Resources" message="Published resources remain available through the User Resources section." />; if (page === "profile" || page === "settings") return <Unavailable title={page[0].toUpperCase() + page.slice(1)} message="Profile and settings continue to use the existing authenticated account settings." />; return null; }
function Overview({ onError }) { const [data, setData] = useState(null); useEffect(() => { let cancelled = false; getProfessionalOverview().then((result) => !cancelled && setData(result.stats)).catch((e) => !cancelled && onError(e.message)); return () => { cancelled = true; }; }, [onError]); if (!data) return <State loading />; return <section className="professional-grid">{[["Today's appointments", data.todayAppointments], ["Upcoming appointments", data.upcomingAppointments], ["Assigned patients", data.assignedPatients], ["Pending requests", data.pendingRequests], ["Completed sessions", data.completedSessions]].map(([label, value]) => <article className="professional-card" key={label}><span>{label}</span><strong>{value}</strong></article>)}</section>; }
function Appointments({ onError }) { const [items, setItems] = useState(null); useEffect(() => { let cancelled = false; getProfessionalAppointments().then((result) => !cancelled && setItems(result.appointments || [])).catch((e) => !cancelled && onError(e.message)); return () => { cancelled = true; }; }, [onError]); if (!items) return <State loading />; return <section className="professional-panel"><h2>Assigned appointments</h2><div className="professional-table-wrap"><table><thead><tr><th>Patient</th><th>Scheduled</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.user?.name}<small>{item.user?.email}</small></td><td>{formatDate(item.startsAt)}</td><td>{item.type}</td><td>{item.status}</td><td><select value={item.status} onChange={(e) => updateProfessionalAppointment(item.id, e.target.value).then((result) => setItems((previous) => previous.map((current) => current.id === item.id ? result.appointment : current))).catch((e) => onError(e.message))}><option>Pending</option><option>Confirmed</option><option>Rejected</option><option>Cancelled</option><option>Completed</option></select></td></tr>)}</tbody></table>{!items.length && <p>No appointments assigned to you.</p>}</div></section>; }
function Patients({ onError }) { const [items, setItems] = useState(null); useEffect(() => { let cancelled = false; getProfessionalPatients().then((result) => !cancelled && setItems(result.patients || [])).catch((e) => !cancelled && onError(e.message)); return () => { cancelled = true; }; }, [onError]); if (!items) return <State loading />; return <section className="professional-panel"><h2>Assigned patients</h2>{items.map((patient) => <div className="professional-list-item" key={patient.id}><UserRound size={18} /><div><strong>{patient.name}</strong><span>{patient.email}</span></div></div>)}{!items.length && <p>No assigned patients.</p>}</section>; }
function Availability({ onError }) { const [data, setData] = useState(null); useEffect(() => { let cancelled = false; getProfessionalAvailability().then((result) => !cancelled && setData(result)).catch((e) => !cancelled && onError(e.message)); return () => { cancelled = true; }; }, [onError]); if (!data) return <State loading />; return <Unavailable title="Availability" message={data.message || "Availability is not configured."} />; }
function Unavailable({ title, message }) { return <section className="professional-panel"><h2>{title}</h2><p>{message}</p></section>; }
